// GENERATED by tools/extract-workbook.py from print/src/wb-part-*.html.
// Do not edit. The printed wording is the wording the screen uses.
export const WORKBOOK = {
 "order": [
  "cover",
  "howitworks",
  "index",
  "whatis",
  "whatsystem",
  "glossary",
  "phasea",
  "s1instr",
  "s1work",
  "s1ref",
  "s1work2",
  "s2instr1",
  "s2work1",
  "s2instr2",
  "s2work2",
  "s2instr3",
  "s2work3",
  "s2draw",
  "s2draw2",
  "s3instr",
  "s3work1",
  "s3ref",
  "s3work2",
  "checks",
  "carries",
  "notes",
  "notes2",
  "backcover"
 ],
 "pages": {
  "cover": {
   "id": "cover",
   "page": 1,
   "kind": "work",
   "tab": null,
   "overline": null,
   "title": null,
   "lead": null,
   "zones": [],
   "texts": [
    "A systems thinking process for policy and intervention design",
    "Name(s)",
    "Phase A. Frame",
    "Started",
    "The case",
    "Workbook"
   ]
  },
  "howitworks": {
   "id": "howitworks",
   "page": 2,
   "kind": "instruction",
   "tab": "How to use this",
   "overline": null,
   "title": "How this workbook works",
   "lead": null,
   "blocks": [
    {
     "h": [
      "Left page tells you, right page is yours"
     ]
    },
    {
     "p": [
      "Every step has an instruction page on the left and a working page on the right. Everything needed to fill the right-hand page is on the left-hand page facing it, so nothing has to be remembered from an earlier step or looked up elsewhere. Read the left page, then write on the right."
     ]
    },
    {
     "p": [
      "The work on each right-hand page is set out as numbered exercises. Do them in the order they are printed."
     ]
    },
    {
     "h": [
      "Moving forwards is checked, backwards is always free"
     ]
    },
    {
     "p": [
      "Each step ends with a ",
      {
       "b": [
        "critical check"
       ]
      },
      ": a short list the participant checks themselves. The step is not finished until every line can be ticked off. Going back, on the other hand, costs nothing and is expected. When a later step shows that an earlier one was wrong, go back, change the earlier work, and write the date and the reason in the strip at the foot of that step's page. Nothing is rubbed out. What was first thought is evidence of where the thinking moved."
     ]
    },
    {
     "p": [
      "Two colours of pen make that visible. Use one colour for everything written the first time, and a second colour for every revision. A page in one colour has either been right first time or has not been revisited, and both are worth noticing."
     ]
    },
    {
     "h": [
      "Nothing here is assessed by filling it in"
     ]
    },
    {
     "p": [
      "A full page is not the point. A page with four actors on it and a good reason for the other eight being left out is a better answer than twelve names."
     ]
    },
    {
     "h": [
      "Where the words are defined"
     ]
    },
    {
     "p": [
      "The glossary on page ",
      {
       "ref": "glossary"
      },
      " gives the short definition of every term this process uses precisely. The longer definition, with what the term excludes and why, is on the instruction page of the step that first uses the term."
     ]
    },
    {
     "h": [
      "The notes pages"
     ]
    },
    {
     "p": [
      "The notes pages at the end, from page ",
      {
       "ref": "notes"
      },
      ", are for anything that does not belong on a working page: questions that could not be answered, sources to find later, and disagreements the group did not settle. They are part of the work rather than a margin."
     ]
    },
    {
     "opposite": [
      "Opposite: the thirteen steps"
     ]
    }
   ]
  },
  "index": {
   "id": "index",
   "page": 3,
   "kind": "work",
   "tab": "How to use this",
   "overline": null,
   "title": "The thirteen steps",
   "lead": [
    "Five phases. This workbook covers ",
    {
     "b": [
      "Phase A"
     ]
    },
    ", which is Steps 1 to 3. The later phases are added to this workbook as they are written."
   ],
   "zones": [],
   "texts": [
    ", which is Steps 1 to 3. The later phases are added to this workbook as they are written.",
    "1",
    "10",
    "11",
    "12",
    "13",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "A",
    "Also in this workbook",
    "Analyse the mapping and write its narrative",
    "Apply",
    "Apply the analysis",
    "B",
    "C",
    "Choose",
    "Communicate to audiences",
    "D",
    "Define the problem, the desired change, and your position",
    "Describe behaviour over time",
    "E",
    "Five phases. This workbook covers",
    "Five phases. This workbook covers Phase A, which is Steps 1 to 3. The later phases are added to this workbook as they are written.",
    "Frame",
    "Glossary",
    "How to use this",
    "Identify enablers and inhibitors",
    "Identify leverage",
    "Map the causal structure",
    "Phase A",
    "Phase A: the critical checks",
    "Phase A: what carries forward",
    "Plan monitoring and learning",
    "Set the boundary and the perspectives",
    "State the intervention hypothesis",
    "Summary and notes",
    "Test and plan",
    "Test the hypothesis",
    "The thirteen steps",
    "Understand",
    "Weigh consequences and interests",
    "What a system is",
    "What systems thinking is",
    "later",
    "{p:carries}",
    "{p:checks}",
    "{p:glossary}",
    "{p:notes}",
    "{p:s1work}",
    "{p:s2work1}",
    "{p:s3work1}",
    "{p:whatis}",
    "{p:whatsystem}"
   ]
  },
  "whatis": {
   "id": "whatis",
   "page": 4,
   "kind": "instruction",
   "tab": "Before you start",
   "overline": null,
   "title": "What systems thinking is",
   "lead": [
    "A way of explaining why a situation keeps producing the same result, by looking at how its parts are connected rather than at the parts one at a time."
   ],
   "blocks": [
    {
     "h": [
      "The starting claim"
     ]
    },
    {
     "p": [
      "Most stubborn problems are not caused by one thing going wrong. They are produced, over and over, by an arrangement that is working exactly as it is arranged. Meadows puts the claim at its strongest: a system, to a large extent, causes its own behaviour (Meadows, 2008, p. 2). An outside event may set the behaviour off, but the same event applied to a differently arranged system produces a different result."
     ]
    },
    {
     "p": [
      "That is why a problem can survive several sincere attempts to solve it. Each attempt acts on a part. The arrangement that produces the problem is left intact, and the arrangement reasserts itself."
     ]
    },
    {
     "h": [
      "What follows from the claim"
     ]
    },
    {
     "list": [
      [
       {
        "b": [
         "Structure produces behaviour."
        ]
       },
       " If a situation keeps returning to the same state, something in the arrangement is returning it. Finding that something is the work."
      ],
      [
       {
        "b": [
         "The explanation is usually circular, not linear."
        ]
       },
       " A affects B, and B affects A. Causes and effects are not in separate columns, which is why a list of causes rarely explains a persistent problem."
      ],
      [
       {
        "b": [
         "Effects arrive late."
        ]
       },
       " What is done now often shows up years later, and the delay is why people conclude that an intervention failed when it has simply not arrived yet."
      ],
      [
       {
        "b": [
         "Where you draw the edge decides what you can explain."
        ]
       },
       " Draw it too tightly and the cause sits outside it; draw it too widely and nothing can be traced."
      ],
      [
       {
        "b": [
         "Nobody sees the whole system."
        ]
       },
       " Everyone involved sees the part they stand in, and each of those views is reasonable from where that person stands. An analysis that treats one of them as simply wrong has given up on explaining the behaviour."
      ]
     ],
     "ordered": true
    },
    {
     "h": [
      "What it is not"
     ]
    },
    {
     "p": [
      "It is not a way of proving what caused something. The output is an explanation good enough to act on, held together by evidence and open to being wrong, and the process keeps saying which parts are evidence and which parts are estimate."
     ]
    },
    {
     "p": [
      "It is also not a way of making a problem bigger. The discipline runs the other way: the edge is drawn deliberately, the number of parts is capped, and everything left out is left out with a reason."
     ]
    },
    {
     "opposite": [
      "Opposite: what a system is"
     ]
    }
   ]
  },
  "whatsystem": {
   "id": "whatsystem",
   "page": 5,
   "kind": "instruction",
   "tab": "Before you start",
   "overline": null,
   "title": "What a system is",
   "lead": null,
   "blocks": [
    {
     "template": [
      "A ",
      {
       "b": [
        "system"
       ]
      },
      " is a set of things, interconnected in such a way that they produce their own pattern of behaviour over time (Meadows, 2008, p. 2)."
     ]
    },
    {
     "h": [
      "The three parts"
     ]
    },
    {
     "p": [
      "A system has to have all three of these, and the order matters less than the fact that none of them can be missing (Meadows, 2008, p. 11)."
     ]
    },
    {
     "table": {
      "head": [
       [
        "Part"
       ],
       [
        "What it means here"
       ]
      ],
      "rows": [
       [
        [
         {
          "b": [
           "Elements"
          ]
         }
        ],
        [
         "The things the system is made of. In this process the elements that matter are the actors, and the quantities that rise and fall"
        ]
       ],
       [
        [
         {
          "b": [
           "Interconnections"
          ]
         }
        ],
        [
         "What links the elements: rules, money, information, who depends on whom. This is where most of the explanation turns out to be"
        ]
       ],
       [
        [
         {
          "b": [
           "A function or purpose"
          ]
         }
        ],
        [
         "What the arrangement produces, judged by what it actually produces rather than by what anyone says it is for"
        ]
       ]
      ]
     }
    },
    {
     "h": [
      "What is not a system"
     ]
    },
    {
     "p": [
      "A collection without interconnections or a function is not a system. Meadows uses sand scattered on a road: add sand or take sand away and there is still just sand on the road. Take a player out of a football team, or a part out of a digestive system, and what remains is a different system (Meadows, 2008, pp. 11 and 12)."
     ]
    },
    {
     "p": [
      "The test is useful in the other direction too. If nothing changes when a part is removed, that part is probably not inside the system being analysed."
     ]
    },
    {
     "h": [
      "Two things that follow, and that this workbook relies on"
     ]
    },
    {
     "p": [
      {
       "b": [
        "A system is more than the sum of its parts."
       ]
      },
      " Listing the parts and describing each one does not explain what the arrangement produces. The interconnections have to be drawn."
     ]
    },
    {
     "p": [
      {
       "b": [
        "The function is read off what is produced, not off what is intended."
       ]
      },
      " A well-meant arrangement that reliably produces a result is, for the purposes of analysis, an arrangement that is set up to produce that result. This is uncomfortable and it is the most useful idea here."
     ]
    },
    {
     "opposite": [
      "Overleaf: the glossary"
     ]
    }
   ]
  },
  "glossary": {
   "id": "glossary",
   "page": 6,
   "kind": "instruction",
   "tab": "Before you start",
   "overline": null,
   "title": "Glossary",
   "lead": [
    "The short definition of each term, and the page where the term is set out in full. Terms are used precisely in this process and are not swapped for near synonyms."
   ],
   "blocks": [
    {
     "opposite": [
      "Opposite: Phase A begins"
     ]
    }
   ],
   "terms": [
    {
     "term": "Actor",
     "definition": "Someone who can act in this system, or is acted upon by it. Four tests admit an actor, and any one of them is enough",
     "ref": "s2instr1"
    },
    {
     "term": "Behaviour",
     "definition": "The system's, not anyone's conduct: the path a quantity has taken over time",
     "ref": "s3instr"
    },
    {
     "term": "Boundary",
     "definition": "The line between what is part of this system and what is next to it but not part of it. Everything outside carries a reason",
     "ref": "s2instr1"
    },
    {
     "term": "Critical check",
     "definition": "The short list at the end of a step, checked by the participant, that has to be complete before the next step starts",
     "ref": "checks"
    },
    {
     "term": "Desired change",
     "definition": "What would be different if the problem improved, said in the same terms as the problem definition and not as a way of getting there",
     "ref": "s1instr"
    },
    {
     "term": "Layer",
     "definition": "A set of actors who work within the same scope of decision-making or implementation, ordered by how far a decision reaches",
     "ref": "s2instr1"
    },
    {
     "term": "Pattern shape",
     "definition": "The name for what a line on a graph does, chosen from a closed list of six",
     "ref": "s3ref"
    },
    {
     "term": "Position",
     "definition": "Who the participant is in relation to this system, chosen from five. It decides what the last steps of the process deliver",
     "ref": "s1ref"
    },
    {
     "term": "Problem definition",
     "definition": "The sentence naming what is wrong with something valued, for whom, since when, and why that matters. Written first as an attempt, then agreed; every later step reads the agreed one",
     "ref": "s1instr"
    },
    {
     "term": "Resources",
     "definition": "The seven kinds of thing an actor can hold that others in the system need",
     "ref": "s2instr2"
    },
    {
     "term": "Stakeholder",
     "definition": "Not used in this process. Everything inside the system is an actor",
     "ref": "s2instr1"
    },
    {
     "term": "System",
     "definition": "A set of things, interconnected in such a way that they produce their own pattern of behaviour over time",
     "ref": "whatsystem"
    },
    {
     "term": "System problem definition",
     "definition": "One sentence naming the pattern the system keeps producing, which is a different sentence from the agreed problem definition",
     "ref": "s3ref"
    }
   ]
  },
  "phasea": {
   "id": "phasea",
   "page": 7,
   "kind": "work",
   "tab": "Phase A",
   "overline": null,
   "title": "Frame",
   "lead": [
    "Three steps that turn a topic into a system with edges: what the problem is, what is inside the system and whose views count, and how the situation has behaved over time."
   ],
   "zones": [],
   "texts": [
    ".",
    "Decides what is inside the system and what is left out, and whose views count.",
    "Define the problem, the desired change, and your position",
    "Describe behaviour over time",
    "Fixes what is being analysed, what change is wanted, and who you are in relation to it.",
    "Frame",
    "Phase A",
    "Phase A is complete when the critical checks on page",
    "Phase A is complete when the critical checks on page {p:checks} can all be ticked off, and what carries forward has been written on page {p:carries}.",
    "Set the boundary and the perspectives",
    "Shows the pattern the system produces.",
    "Step 1 · page",
    "Step 1 · page {p:s1work}",
    "Step 2 · page",
    "Step 2 · page {p:s2work1}",
    "Step 3 · page",
    "Step 3 · page {p:s3work1}",
    "Three steps that turn a topic into a system with edges: what the problem is, what is inside the system and whose views count, and how the situation has behaved over time.",
    "can all be ticked off, and what carries forward has been written on page"
   ]
  },
  "s1instr": {
   "id": "s1instr",
   "page": 8,
   "kind": "instruction",
   "tab": "Step 1",
   "overline": "Step 1 · before you write",
   "title": "Define the problem",
   "lead": [
    "To fix what is being analysed, what change is wanted, and who you are in relation to it, before any explaining starts."
   ],
   "blocks": [
    {
     "h": [
      "The problem definition"
     ]
    },
    {
     "p": [
      "The problem is written as one sentence in a fixed form. That sentence is called the ",
      {
       "b": [
        "problem definition"
       ]
      },
      " throughout this workbook."
     ]
    },
    {
     "template": [
      "There is ",
      {
       "b": [
        "too much"
       ]
      },
      " (or ",
      {
       "b": [
        "too little"
       ]
      },
      ") of ",
      {
       "b": [
        "[thing]"
       ]
      },
      " for ",
      {
       "b": [
        "[who]"
       ]
      },
      ", since ",
      {
       "b": [
        "[when]"
       ]
      },
      ", which matters because ",
      {
       "b": [
        "[consequence]"
       ]
      },
      "."
     ]
    },
    {
     "p": [
      "Then a short rationale saying how and why people are affected. Where the reason it matters is that something is unfair, the rationale says who is affected, compared with whom, and against which expectation. Two questions are worth answering in the rationale: what is at stake, and why do we care? What is driving us to think about this now?"
     ]
    },
    {
     "p": [
      "This form does not fit every problem. Three other forms, and when each is needed, are on page ",
      {
       "ref": "s1ref"
      },
      "."
     ]
    },
    {
     "h": [
      "Eight rules, read against the finished problem definition"
     ]
    },
    {
     "list": [
      [
       {
        "b": [
         "One problem per definition."
        ]
       },
       " If the sentence needs \"and\" to hold two things, there are two problems."
      ],
      [
       {
        "b": [
         "Name a thing that can rise or fall."
        ]
       },
       " Not \"the system is failing\", which cannot rise or fall, but \"the share of applications decided within the legal term\", which can."
      ],
      [
       {
        "b": [
         "No solution in the definition."
        ]
       },
       " An action, an instrument, or an organisation that should act is a potential solution: keep it for later, not in the sentence."
      ],
      [
       {
        "b": [
         "No cause in the definition."
        ]
       },
       " \"Because the ministry underfunds it\" is an answer the analysis has to earn, not a premise to start from."
      ],
      [
       {
        "b": [
         "No blame in the definition."
        ]
       },
       " Rewrite it so that someone who disagrees about the cause could still accept the sentence as a description."
      ],
      [
       {
        "b": [
         "Bound it."
        ]
       },
       " Place, population, and period, so that the questions in Exercise 3 can be answered."
      ],
      [
       {
        "b": [
         "A value can be the reason, not the fact."
        ]
       },
       " \"This is unfair\" is why it matters. The definition itself still needs what there is too much or too little of."
      ],
      [
       {
        "b": [
         "Plain words."
        ]
       },
       " If a term would need explaining to someone outside the field, define it in the rationale or drop it."
      ]
     ],
     "ordered": true
    },
    {
     "h": [
      "On neutrality"
     ]
    },
    {
     "p": [
      "The problem definition is not value neutral and does not pretend to be. Calling something too little or too much implies an expectation about what the level should be. The rule is that the expectation is named in the rationale rather than hidden in an adjective. \"Too few inspections\" hides the expectation. \"Fewer inspections than the twice-yearly minimum the regulation sets\" names it."
     ]
    },
    {
     "opposite": [
      "Opposite: Exercises 1 to 5"
     ]
    }
   ]
  },
  "s1work": {
   "id": "s1work",
   "page": 9,
   "kind": "work",
   "tab": "Step 1",
   "overline": "Step 1 · your page",
   "title": "Define the problem",
   "lead": null,
   "zones": [
    {
     "number": "1",
     "label": "Exercise 1",
     "title": "The situation",
     "hints": [
      "In your own words, what is going on? A warm-up, not the problem definition."
     ],
     "hintsInline": [
      [
       "In your own words, what is going on? A warm-up, not the problem definition."
      ]
     ],
     "texts": [
      "1",
      "Exercise 1",
      "In your own words, what is going on? A warm-up, not the problem definition.",
      "The situation"
     ]
    },
    {
     "number": "2",
     "label": "Exercise 2",
     "title": "The problem definition, first attempt",
     "hints": [
      "The rationale: how and why people are affected."
     ],
     "hintsInline": [
      [
       "The rationale: how and why people are affected."
      ]
     ],
     "texts": [
      "2",
      "Exercise 2",
      "The problem definition, first attempt",
      "The rationale: how and why people are affected.",
      "There is",
      "There is[ ] too much [ ] too little",
      "[ ] too much [ ] too little",
      "for",
      "since",
      "the consequence",
      "the thing there is too much or too little of",
      "when",
      "which matters because",
      "who it affects"
     ]
    },
    {
     "number": "3",
     "label": "Exercise 3",
     "title": "Is this the kind of problem this process is for?",
     "hints": [
      "A yes means the problem is a decision that nobody has taken, not a system that keeps producing a result. Choose a different topic."
     ],
     "hintsInline": [
      [
       "A yes means the problem is a decision that nobody has taken, not a system that keeps producing a result. Choose a different topic."
      ]
     ],
     "texts": [
      "3",
      "A yes means the problem is a decision that nobody has taken, not a system that keeps producing a result. Choose a different topic.",
      "Can you say where the problem starts and stops, and foresee about a dozen things that drive it?",
      "Could a known procedure solve this, if someone chose to?",
      "Does it have a history you can describe?",
      "Exercise 3",
      "Have previous attempts to deal with it failed?",
      "How you know",
      "Is this an ongoing problem, rather than something that happened once?",
      "Is this the kind of problem this process is for?",
      "N",
      "One question disqualifies a topic.",
      "Y",
      "YN"
     ]
    },
    {
     "number": "4",
     "label": "Exercise 4",
     "title": "The desired change",
     "hints": [
      "In the same terms as the problem definition in Exercise 2. Not how to get there."
     ],
     "hintsInline": [
      [
       "In the same terms as the problem definition in Exercise 2. Not how to get there."
      ]
     ],
     "texts": [
      "4",
      "A nearer point, one to five years out",
      "A nearer point, one to five years outYear",
      "Exercise 4",
      "In five years or more",
      "In five years or moreYear",
      "In the same terms as the problem definition in Exercise 2. Not how to get there.",
      "The desired change",
      "Year"
     ]
    },
    {
     "number": "5",
     "label": "Exercise 5",
     "title": "Your position",
     "hints": [
      "Or one of these, each of which acts for or advises someone:"
     ],
     "hintsInline": [
      [
       "Or one of these, each of which acts for or advises someone:"
      ]
     ],
     "texts": [
      "5",
      "Acting for an organisation or a cause",
      "Acting for an organisation or a cause Advising someone who decides Deciding, or my organisation does Affected by this",
      "Advising someone who decides",
      "Affected by this",
      "Analysing from outside, with no client and no organisation",
      "Deciding, or my organisation does",
      "Exercise 5",
      "If one of those four, on whose behalf?",
      "Or one of these, each of which acts for or advises someone:",
      "Your position"
     ]
    }
   ],
   "texts": [
    "1",
    "2",
    "3",
    "4",
    "5",
    "A nearer point, one to five years out",
    "A nearer point, one to five years outYear",
    "A yes means the problem is a decision that nobody has taken, not a system that keeps producing a result. Choose a different topic.",
    "Acting for an organisation or a cause",
    "Acting for an organisation or a cause Advising someone who decides Deciding, or my organisation does Affected by this",
    "Advising someone who decides",
    "Affected by this",
    "Analysing from outside, with no client and no organisation",
    "Can you say where the problem starts and stops, and foresee about a dozen things that drive it?",
    "Could a known procedure solve this, if someone chose to?",
    "Deciding, or my organisation does",
    "Define the problem",
    "Does it have a history you can describe?",
    "Exercise 1",
    "Exercise 2",
    "Exercise 3",
    "Exercise 4",
    "Exercise 5",
    "Have previous attempts to deal with it failed?",
    "How you know",
    "If one of those four, on whose behalf?",
    "In five years or more",
    "In five years or moreYear",
    "In the same terms as the problem definition in Exercise 2. Not how to get there.",
    "In your own words, what is going on? A warm-up, not the problem definition.",
    "Is this an ongoing problem, rather than something that happened once?",
    "Is this the kind of problem this process is for?",
    "N",
    "One question disqualifies a topic.",
    "Or one of these, each of which acts for or advises someone:",
    "Revised on",
    "Revised on because",
    "Step 1",
    "Step 1 · your page",
    "The desired change",
    "The problem definition, first attempt",
    "The rationale: how and why people are affected.",
    "The situation",
    "There is",
    "There is[ ] too much [ ] too little",
    "Y",
    "YN",
    "Year",
    "Your position",
    "[ ] too much [ ] too little",
    "because",
    "for",
    "since",
    "the consequence",
    "the thing there is too much or too little of",
    "when",
    "which matters because",
    "who it affects"
   ]
  },
  "s1ref": {
   "id": "s1ref",
   "page": 10,
   "kind": "instruction",
   "tab": "Step 1",
   "overline": "Step 1 · before Exercises 6 to 8",
   "title": "Other forms, positions, and size",
   "lead": null,
   "blocks": [
    {
     "h": [
      "The check before Exercise 6"
     ]
    },
    {
     "p": [
      "Read the problem definition in Exercise 2 against two questions. Could someone who disagrees about the cause still accept the problem definition as a description? Could that person say what would have to change for the problem definition to stop being true? If either answer is no, the problem definition is carrying a cause, a blame, or a solution, and needs to be rewritten in Exercise 6. If both answers are yes, copy the first attempt across to Exercise 6 as it stands. Either way, the agreed problem definition is always written in Exercise 6, because it is the one every later step reads."
     ]
    },
    {
     "h": [
      "When too much and too little does not fit"
     ]
    },
    {
     "p": [
      "The form on page ",
      {
       "ref": "s1instr"
      },
      " is the default, not the only one. Take these in order, and choose one only with a line saying why the default did not fit. All of them carry the same five parts: the thing, the direction or the gap, who it affects, since when, and why it matters."
     ]
    },
    {
     "table": {
      "head": [
       [
        "Form"
       ],
       [
        "Use it when, and how to write it"
       ]
      ],
      "rows": [
       [
        [
         {
          "b": [
           "Mismatch"
          ]
         }
        ],
        [
         "The quantity is right, but it is in the wrong place, at the wrong time, or with the wrong people. ",
         {
          "i": [
           "X exists, but not where (or when, or for whom) it is needed: it is at A while the need is at B."
          ]
         }
        ]
       ],
       [
        [
         {
          "b": [
           "Falling short of a standard"
          ]
         }
        ],
        [
         "The thing exists and is counted, but fails a rule, a promise, or a quality that was set. ",
         {
          "i": [
           "X falls short of Y: the standard says A, the practice is B."
          ]
         }
        ]
       ],
       [
        [
         {
          "b": [
           "Not happened yet"
          ]
         }
        ],
        [
         "A risk, or a capacity that does not exist at all. There is no series to be too high or too low. ",
         {
          "i": [
           "If A continues, B becomes likely, and nothing currently prevents it."
          ]
         }
        ]
       ]
      ]
     }
    },
    {
     "h": [
      "The five positions, and what each one changes"
     ]
    },
    {
     "p": [
      "Your position decides what the analysis ends in, so it is chosen once and carried through."
     ]
    },
    {
     "table": {
      "head": [
       [
        "Position"
       ],
       [
        "What the analysis ends in"
       ]
      ],
      "rows": [
       [
        [
         "Analysing from outside"
        ],
        [
         "Findings. Your own influence is not part of the analysis"
        ]
       ],
       [
        [
         "Acting for an organisation or a cause"
        ],
        [
         "A target and an ask. Your own influence is part of the analysis"
        ]
       ],
       [
        [
         "Advising someone who decides"
        ],
        [
         "Options with a recommendation. The reach that counts is the client's, not yours"
        ]
       ],
       [
        [
         "Deciding, or your organisation does"
        ],
        [
         "A decision. What is inside your own control is looked at first"
        ]
       ],
       [
        [
         "Affected by this"
        ],
        [
         "A route through an organisation or a coalition, because the power available is mostly power with others"
        ]
       ]
      ]
     }
    },
    {
     "h": [
      "If the problem is too large, or too small"
     ]
    },
    {
     "p": [
      "Exercise 3 is how you know. If you cannot say where the problem starts and stops, or cannot foresee about a dozen things that drive it, it is too large. If almost nothing drives it, it is too small."
     ]
    },
    {
     "p": [
      {
       "b": [
        "Narrow"
       ]
      },
      " by place, by population, by a single decision, or by period. ",
      {
       "b": [
        "Widen"
       ]
      },
      " by asking why the situation persists, or by taking in the decision that sets the conditions for it. The size question in Exercise 3 is a judgement rather than a rule: it asks whether the problem is small enough to work on and still large enough to be worth explaining."
     ]
    },
    {
     "h": [
      "How others describe it, in Exercise 7"
     ]
    },
    {
     "p": [
      "Find how the problem is currently described by those with power over it: a policy document, a press release, a minister's answer, an annual report, a minutes entry. Write their description in their words, not yours, and then write what that description takes for granted and what it leaves out. Give the source. One description is enough here; the others come later."
     ]
    },
    {
     "opposite": [
      "Opposite: Exercises 6 to 8"
     ]
    }
   ]
  },
  "s1work2": {
   "id": "s1work2",
   "page": 11,
   "kind": "work",
   "tab": "Step 1",
   "overline": "Step 1 · your page",
   "title": "The agreed problem definition",
   "lead": [
    "Almost every first attempt carries a cause, a blame, or a solution. Write the agreed problem definition here, rewritten or copied across, rather than crossing out the first attempt, so that both are visible."
   ],
   "zones": [
    {
     "number": "6",
     "label": "Exercise 6",
     "title": "The problem definition, agreed",
     "hints": [],
     "hintsInline": [],
     "texts": [
      "6",
      "Exercise 6",
      "Falling short of a standard",
      "If not the default form, why it did not fit",
      "Mismatch",
      "Not happened yet",
      "The problem definition, agreed",
      "Too much or too little",
      "Too much or too littleMismatch Falling short of a standardNot happened yet",
      "since when",
      "the thing",
      "what is wrong with it",
      "which matters because",
      "who it affects"
     ]
    },
    {
     "number": "7",
     "label": "Exercise 7",
     "title": "How others describe it",
     "hints": [
      "In their words. Then what that description takes for granted."
     ],
     "hintsInline": [
      [
       "In their words. Then what that description takes for granted."
      ]
     ],
     "texts": [
      "7",
      "Exercise 7",
      "How others describe it",
      "In their words. Then what that description takes for granted.",
      "What that description leaves out",
      "Where you read it"
     ]
    },
    {
     "number": "8",
     "label": "Exercise 8",
     "title": "Potential solutions, for later",
     "hints": [
      "Potential solutions that occur to you go here, not in the agreed problem definition."
     ],
     "hintsInline": [
      [
       "Potential solutions that occur to you go here, not in the agreed problem definition."
      ]
     ],
     "texts": [
      "8",
      "Exercise 8",
      "Potential solutions that occur to you go here, not in the agreed problem definition.",
      "Potential solutions, for later"
     ]
    }
   ],
   "texts": [
    "6",
    "7",
    "8",
    "Almost every first attempt carries a cause, a blame, or a solution. Write the agreed problem definition here, rewritten or copied across, rather than crossing out the first attempt, so that both are visible.",
    "Exercise 6",
    "Exercise 7",
    "Exercise 8",
    "Falling short of a standard",
    "How others describe it",
    "If not the default form, why it did not fit",
    "In their words. Then what that description takes for granted.",
    "Mismatch",
    "Not happened yet",
    "Potential solutions that occur to you go here, not in the agreed problem definition.",
    "Potential solutions, for later",
    "Revised on",
    "Revised on because",
    "Step 1",
    "Step 1 · your page",
    "The agreed problem definition",
    "The problem definition, agreed",
    "Too much or too little",
    "Too much or too littleMismatch Falling short of a standardNot happened yet",
    "What that description leaves out",
    "Where you read it",
    "because",
    "since when",
    "the thing",
    "what is wrong with it",
    "which matters because",
    "who it affects"
   ]
  },
  "s2instr1": {
   "id": "s2instr1",
   "page": 12,
   "kind": "instruction",
   "tab": "Step 2",
   "overline": "Step 2 · before you begin",
   "title": "Set the boundary and the perspectives",
   "lead": [
    "To decide what is inside the system and what is left out, and whose views count. This is where the case stops being a topic and becomes a system with edges."
   ],
   "blocks": [
    {
     "h": [
      "Four words this step uses precisely"
     ]
    },
    {
     "p": [
      {
       "b": [
        "Actor."
       ]
      },
      " Someone who can act in this system or is acted upon by it. Any one of four tests admits an actor: ",
      {
       "b": [
        "1"
       ]
      },
      " they do something that affects the problem, ",
      {
       "b": [
        "2"
       ]
      },
      " they are affected by what the system produces, ",
      {
       "b": [
        "3"
       ]
      },
      " they hold something others in the system need, or ",
      {
       "b": [
        "4"
       ]
      },
      " they can start or stop a change. Two things are not actors: a category with no agency, such as the weather, the market, or society, which is a condition rather than an actor; and a named individual, unless the thing held belongs to that person rather than to their organisation."
     ]
    },
    {
     "p": [
      {
       "b": [
        "Layer."
       ]
      },
      " A set of actors who work within the same scope of decision-making or implementation, meaning that what any of them decides applies to the same territory, population, or part of the organisation. Layers are ordered by how far a decision reaches, from the widest scope of decision to the narrowest, and by nothing else. They are not ranks, not importance, and not a chain of command. They belong to the system, not to you."
     ]
    },
    {
     "p": [
      {
       "b": [
        "Actor type."
       ]
      },
      " What kind of actor this is, in this case. The list is written by the participant, at most five types, and as a guide no more than one type per three actors. An actor that seems to need two types usually means the type list is wrong rather than the actor."
     ]
    },
    {
     "p": [
      {
       "b": [
        "Stakeholder"
       ]
      },
      " is not used in this process. Everything inside the system is an actor."
     ]
    },
    {
     "h": [
      "Drawing the boundary"
     ]
    },
    {
     "p": [
      "Almost everything is connected to almost everything else, so \"is this related?\" admits everything. The test is difference, not relevance: ",
      {
       "b": [
        "would including this change what the analysis concludes?"
       ]
      },
      " A candidate goes inside if any one of three things is true. The candidate can increase or decrease the quantity named in the agreed problem definition. The candidate is on the receiving end of the excess or deficit of that quantity, meaning the candidate is part of who the problem is for. Or the candidate sets the rules the first two work under."
     ]
    },
    {
     "p": [
      "Everything left out is marked ",
      {
       "b": [
        "F"
       ]
      },
      " fixed, ",
      {
       "b": [
        "O"
       ]
      },
      " out of reach, or ",
      {
       "b": [
        "I"
       ]
      },
      " irrelevant, with one line of reason. Fixed means it will not change during the period being analysed. Out of reach means it could change but nobody in this case can affect it. Irrelevant means including it would not change what the analysis concludes."
     ]
    },
    {
     "p": [
      "The boundary stays provisional. Everything marked F or O is written down rather than forgotten, because a thing assumed fixed that turns out to move is the commonest reason an intervention fails."
     ]
    },
    {
     "h": [
      "How many actors"
     ]
    },
    {
     "p": [
      "About a dozen. Past roughly fifteen, either the granularity or the boundary has gone wrong: individual officials are being listed where the department that decides is the actor, or the boundary has taken in layers where nobody passes any of the three tests above. Check granularity first."
     ]
    },
    {
     "opposite": [
      "Opposite: Exercises 1 to 4"
     ]
    }
   ]
  },
  "s2work1": {
   "id": "s2work1",
   "page": 13,
   "kind": "work",
   "tab": "Step 2",
   "overline": "Step 2 · your page",
   "title": "The boundary, the layers, and the types",
   "lead": null,
   "zones": [
    {
     "number": "1",
     "label": "Exercise 1 · on a large sheet, not in this book",
     "title": "Draw the system",
     "hints": [
      "Put everything you know about this case onto one large sheet. Pictures and symbols rather than sentences, phrases rather than paragraphs, and show who is in conflict with whom. Use marks for money, for conflict, for a blockage, and a question mark for what you do not know. Work standing up, with the sheet flat on a table or on a wall. Nothing on it has to be tidy."
     ],
     "hintsInline": [
      [
       "Put everything you know about this case onto one large sheet. Pictures and symbols rather than sentences, phrases rather than paragraphs, and show who is in conflict with whom. Use marks for money, for conflict, for a blockage, and a question mark for what you do not know. Work standing up, with the sheet flat on a table or on a wall. Nothing on it has to be tidy."
      ]
     ],
     "texts": [
      "1",
      "Draw the system",
      "Exercise 1 ·",
      "Exercise 1 · on a large sheet, not in this book",
      "Put everything you know about this case onto one large sheet. Pictures and symbols rather than sentences, phrases rather than paragraphs, and show who is in conflict with whom. Use marks for money, for conflict, for a blockage, and a question mark for what you do not know. Work standing up, with the sheet flat on a table or on a wall. Nothing on it has to be tidy.",
      "on a large sheet, not in this book"
     ]
    },
    {
     "number": "2",
     "label": "Exercise 2",
     "title": "What is part of this system, and what is not",
     "hints": [
      "List the actors, and anything else that affects the problem: a rule, a flow of money, a procedure. Everything on the right is marked F fixed, O out of reach, or I irrelevant, with a reason."
     ],
     "hintsInline": [
      [
       "List the actors, and anything else that affects the problem: a rule, a flow of money, a procedure. Everything on the right is marked F fixed, O out of reach, or I irrelevant, with a reason."
      ]
     ],
     "texts": [
      ".",
      "2",
      "Because",
      "Exercise 2",
      "F",
      "FOI",
      "I",
      "List the actors, and anything else that affects the problem: a rule, a flow of money, a procedure. Everything on the right is marked F fixed, O out of reach, or I irrelevant, with a reason.",
      "More rows than these go on the notes pages, from page",
      "More rows than these go on the notes pages, from page {p:notes}.",
      "Next to it, but not part of it",
      "O",
      "Part of this system",
      "What is part of this system, and what is not"
     ]
    },
    {
     "number": "3",
     "label": "Exercise 3",
     "title": "The layers",
     "hints": [
      "Ordered by how far a decision reaches, widest scope of decision first. The narrowest layer goes on row 5, and any layers between on rows 2 to 4. Three to five, and five is the limit. Two only if you write why this case has no third scope of decision, on row 3."
     ],
     "hintsInline": [
      [
       "Ordered by how far a decision reaches, widest scope of decision first. The narrowest layer goes on row 5, and any layers between on rows 2 to 4. Three to five, and five is the limit. Two only if you write why this case has no third scope of decision, on row 3."
      ]
     ],
     "texts": [
      "1",
      "1why this is the widest scope",
      "2",
      "2why this scope sits here",
      "3",
      "3why this scope sits here",
      "4",
      "4why this scope sits here",
      "5",
      "5why this is the narrowest scope",
      "Exercise 3",
      "Ordered by how far a decision reaches, widest scope of decision first. The narrowest layer goes on row 5, and any layers between on rows 2 to 4. Three to five, and five is the limit. Two only if you write why this case has no third scope of decision, on row 3.",
      "The layers",
      "why this is the narrowest scope",
      "why this is the widest scope",
      "why this scope sits here"
     ]
    },
    {
     "number": "4",
     "label": "Exercise 4",
     "title": "The actor types",
     "hints": [
      "At most five. As a guide, no more than one type per three actors."
     ],
     "hintsInline": [
      [
       "At most five. As a guide, no more than one type per three actors."
      ]
     ],
     "texts": [
      "4",
      "A",
      "At most five. As a guide, no more than one type per three actors.",
      "B",
      "C",
      "D",
      "E",
      "Exercise 4",
      "The actor types"
     ]
    }
   ],
   "texts": [
    ".",
    "1",
    "1why this is the widest scope",
    "2",
    "2why this scope sits here",
    "3",
    "3why this scope sits here",
    "4",
    "4why this scope sits here",
    "5",
    "5why this is the narrowest scope",
    "A",
    "At most five. As a guide, no more than one type per three actors.",
    "B",
    "Because",
    "C",
    "D",
    "Draw the system",
    "E",
    "Exercise 1 ·",
    "Exercise 1 · on a large sheet, not in this book",
    "Exercise 2",
    "Exercise 3",
    "Exercise 4",
    "F",
    "FOI",
    "I",
    "List the actors, and anything else that affects the problem: a rule, a flow of money, a procedure. Everything on the right is marked F fixed, O out of reach, or I irrelevant, with a reason.",
    "More rows than these go on the notes pages, from page",
    "More rows than these go on the notes pages, from page {p:notes}.",
    "Next to it, but not part of it",
    "O",
    "Ordered by how far a decision reaches, widest scope of decision first. The narrowest layer goes on row 5, and any layers between on rows 2 to 4. Three to five, and five is the limit. Two only if you write why this case has no third scope of decision, on row 3.",
    "Part of this system",
    "Put everything you know about this case onto one large sheet. Pictures and symbols rather than sentences, phrases rather than paragraphs, and show who is in conflict with whom. Use marks for money, for conflict, for a blockage, and a question mark for what you do not know. Work standing up, with the sheet flat on a table or on a wall. Nothing on it has to be tidy.",
    "Revised on",
    "Revised on because",
    "Step 2",
    "Step 2 · your page",
    "The actor types",
    "The boundary, the layers, and the types",
    "The layers",
    "What is part of this system, and what is not",
    "because",
    "on a large sheet, not in this book",
    "why this is the narrowest scope",
    "why this is the widest scope",
    "why this scope sits here"
   ]
  },
  "s2instr2": {
   "id": "s2instr2",
   "page": 14,
   "kind": "instruction",
   "tab": "Step 2",
   "overline": "Step 2 · before Exercise 5",
   "title": "The resources an actor holds",
   "lead": null,
   "blocks": [
    {
     "h": [
      "Power, and why this step records resources instead"
     ]
    },
    {
     "p": [
      {
       "b": [
        "Power"
       ]
      },
      " here is an actor's capacity to affect what the system does: what gets decided, what reaches the agenda, and what goes unquestioned. That capacity is hard to judge directly and easy to guess at. What can be recorded instead is concrete: the ",
      {
       "b": [
        "resources"
       ]
      },
      " an actor holds that others in the system need. Recording the resources is this step's work; judging what kind of power they add up to comes later, once there is something to judge it against."
     ]
    },
    {
     "h": [
      "The seven resources"
     ]
    },
    {
     "p": [
      "Seven kinds, enough to sort by and few enough to remember."
     ]
    },
    {
     "table": {
      "head": [
       [
        "Resource"
       ],
       [
        "What it means"
       ]
      ],
      "rows": [
       [
        [
         {
          "b": [
           "Formal authority"
          ]
         }
        ],
        [
         "Can decide, or change a rule"
        ]
       ],
       [
        [
         {
          "b": [
           "Money"
          ]
         }
        ],
        [
         "Holds or can redirect the funding"
        ]
       ],
       [
        [
         {
          "b": [
           "Delivery capacity"
          ]
         }
        ],
        [
         "Does the work on the ground"
        ]
       ],
       [
        [
         {
          "b": [
           "Information and expertise"
          ]
         }
        ],
        [
         "Knows something the others need to know"
        ]
       ],
       [
        [
         {
          "b": [
           "Access"
          ]
         }
        ],
        [
         "Can get to whoever decides"
        ]
       ],
       [
        [
         {
          "b": [
           "Legitimacy"
          ]
         }
        ],
        [
         "Can credibly speak for others"
        ]
       ],
       [
        [
         {
          "b": [
           "Public attention"
          ]
         }
        ],
        [
         "Can make an issue visible, or keep it quiet"
        ]
       ]
      ]
     }
    },
    {
     "h": [
      "Two rules while you fill the table"
     ]
    },
    {
     "list": [
      [
       "An actor that seems to need two layers is usually two actors, as a ministry's policy directorate and its inspectorate are two actors with different reach."
      ],
      [
       "An affected group that splits into halves wanting different things is two actors. A single entry that hides the split will not survive the rest of the analysis."
      ]
     ],
     "ordered": true
    },
    {
     "h": [
      "A third rule, about who gets left out"
     ]
    },
    {
     "p": [
      "Include those the system acts on, not only those who act. Name the group by its position in the system (\"households refused on income grounds since 2023\")."
     ]
    },
    {
     "h": [
      "The four columns before the resources"
     ]
    },
    {
     "p": [
      "Columns ",
      {
       "b": [
        "1"
       ]
      },
      " to ",
      {
       "b": [
        "4"
       ]
      },
      " are the four admission tests from page ",
      {
       "ref": "s2instr1"
      },
      ": ",
      {
       "b": [
        "1"
       ]
      },
      " affects the problem, ",
      {
       "b": [
        "2"
       ]
      },
      " is affected by what the system produces, ",
      {
       "b": [
        "3"
       ]
      },
      " holds something others need, ",
      {
       "b": [
        "4"
       ]
      },
      " can start or stop a change. Tick every one that applies. An actor with no tick in any of the four does not belong in the table, and column ",
      {
       "b": [
        "2"
       ]
      },
      " is the one to read back: if nothing is ticked down that column, the list has only the actors who act, and not those the system acts on."
     ]
    },
    {
     "opposite": [
      "Opposite: Exercise 5. Turn the book sideways."
     ]
    }
   ]
  },
  "s2work2": {
   "id": "s2work2",
   "page": 15,
   "kind": "work",
   "tab": "Step 2",
   "overline": null,
   "title": "The actors, and the resources each one holds",
   "lead": null,
   "zones": [],
   "texts": [
    "1",
    "2",
    "3",
    "4",
    "About a dozen is the target. The fifteenth row is the limit: past it, check the granularity first and then the boundary.",
    "Access",
    "Actor",
    "Admitted by",
    "Attention",
    "Authority",
    "Delivery",
    "Exercise 5",
    "Information",
    "Layer",
    "Legitimacy",
    "Money",
    "Resources held",
    "Step 2",
    "The actors, and the resources each one holds",
    "Type"
   ]
  },
  "s2instr3": {
   "id": "s2instr3",
   "page": 16,
   "kind": "instruction",
   "tab": "Step 2",
   "overline": "Step 2 · before Exercises 6 to 9",
   "title": "Who decides, and who disagrees",
   "lead": null,
   "blocks": [
    {
     "h": [
      "Authority, responsibility, and accountability are three different things"
     ]
    },
    {
     "table": {
      "head": [
       [
        "Term"
       ],
       [
        "The question it answers"
       ],
       [
        "Where the answer usually is"
       ]
      ],
      "rows": [
       [
        [
         {
          "b": [
           "Authority"
          ]
         }
        ],
        [
         "Who can take this decision, or change the rule the decision is made under?"
        ],
        [
         "A statute, a mandate, a delegation, a budget line someone can redirect"
        ]
       ],
       [
        [
         {
          "b": [
           "Responsibility"
          ]
         }
        ],
        [
         "Who is tasked with carrying this decision out?"
        ],
        [
         "A work programme, a contract, an implementation plan, a job description"
        ]
       ],
       [
        [
         {
          "b": [
           "Accountability"
          ]
         }
        ],
        [
         "Who is called to answer when what was decided goes wrong?"
        ],
        [
         "An inspection regime, a reporting duty, an election, a complaints procedure"
        ]
       ]
      ]
     }
    },
    {
     "p": [
      "A layer can hold one without the others, and where the three sit apart that is the finding rather than a complication. It is often the finding: the layer that answers for a failure is frequently not the layer that could have prevented it."
     ]
    },
    {
     "h": [
      "Who the dependency question is asked for"
     ]
    },
    {
     "p": [
      "Every actor's resources are recorded in Exercise 5. The second half, who needs each resource from them, is asked only for a subset. The subset is not a matter of your sense of importance: it is read off the allocation in Exercise 6, and completed while you fill Exercise 7. Any actor in a layer holding authority, responsibility, or accountability for the decision, and anyone who holds something those actors need. That is usually three to six actors. Every other actor keeps the ticks in Exercise 5 and nothing more, and that blank is a state rather than an omission."
     ]
    },
    {
     "h": [
      "How the actors see the problem"
     ]
    },
    {
     "p": [
      "This is not the question from Step 1 asked twice. Step 1 recorded one description, the one used by those with power over the issue. Here you ask what each actor takes the problem to be, in that actor's own terms, and what that follows from. One line per actor, for the actors whose reading differs from one already written."
     ]
    },
    {
     "p": [
      "Mark each line ",
      {
       "b": [
        "evidenced"
       ]
      },
      " (a document, a quoted statement, a meeting, an interview) or ",
      {
       "b": [
        "inferred"
       ]
      },
      ". An inferred line is not guesswork: it names what it is read from. A line that cannot name what it is read from is a guess and stays out. Motive is always a guess, so record what an actor treats as the problem, never why that actor privately wants it."
     ]
    },
    {
     "p": [
      "At least two of the descriptions need to differ in a way that matters, meaning both cannot be acted on at once. Two wordings of the same description do not count. Nothing here asks whether a description is correct."
     ]
    },
    {
     "h": [
      "Who speaks for the groups the system acts on"
     ]
    },
    {
     "p": [
      "For each group the system acts on, write the group and who currently speaks for that group on the line under Exercise 9, including \"nobody\"."
     ]
    },
    {
     "opposite": [
      "Opposite: Exercises 6 to 9"
     ]
    }
   ]
  },
  "s2work3": {
   "id": "s2work3",
   "page": 17,
   "kind": "work",
   "tab": "Step 2",
   "overline": "Step 2 · your page",
   "title": "The decision, the dependencies, and the views",
   "lead": null,
   "zones": [
    {
     "number": "6",
     "label": "Exercise 6",
     "title": "Authority, responsibility, and accountability",
     "hints": [
      "\"Nobody\" is an allowed answer."
     ],
     "hintsInline": [
      [
       "\"Nobody\" is an allowed answer."
      ]
     ],
     "texts": [
      "\"Nobody\" is an allowed answer.",
      "6",
      "Accountability",
      "Authority",
      "Authority, responsibility, and accountability",
      "Exercise 6",
      "Responsibility",
      "The decision the desired change depends on"
     ]
    },
    {
     "number": "7",
     "label": "Exercise 7",
     "title": "Who needs what from whom",
     "hints": [],
     "hintsInline": [],
     "texts": [
      ".",
      "7",
      "Actor",
      "Exercise 7",
      "More rows than these go on the notes pages, from page",
      "More rows than these go on the notes pages, from page {p:notes}.",
      "Resource held",
      "Who needs it, and for what",
      "Who needs what from whom"
     ]
    },
    {
     "number": "8",
     "label": "Exercise 8",
     "title": "How the actors see the problem",
     "hints": [],
     "hintsInline": [],
     "texts": [
      "8",
      "Actor",
      "Ev. / inf.",
      "Exercise 8",
      "How the actors see the problem",
      "Read from what?",
      "What they take the problem to be"
     ]
    },
    {
     "number": "9",
     "label": "Exercise 9",
     "title": "Who is not in this list, and why not?",
     "hints": [],
     "hintsInline": [],
     "texts": [
      "9",
      "Exercise 9",
      "Who is not in this list, and why not?",
      "Who speaks for each group the system acts on, including nobody"
     ]
    }
   ],
   "texts": [
    "\"Nobody\" is an allowed answer.",
    ".",
    "6",
    "7",
    "8",
    "9",
    "Accountability",
    "Actor",
    "Authority",
    "Authority, responsibility, and accountability",
    "Ev. / inf.",
    "Exercise 6",
    "Exercise 7",
    "Exercise 8",
    "Exercise 9",
    "How the actors see the problem",
    "More rows than these go on the notes pages, from page",
    "More rows than these go on the notes pages, from page {p:notes}.",
    "Read from what?",
    "Resource held",
    "Responsibility",
    "Revised on",
    "Revised on because",
    "Step 2",
    "Step 2 · your page",
    "The decision the desired change depends on",
    "The decision, the dependencies, and the views",
    "What they take the problem to be",
    "Who is not in this list, and why not?",
    "Who needs it, and for what",
    "Who needs what from whom",
    "Who speaks for each group the system acts on, including nobody",
    "because"
   ]
  },
  "s2draw": {
   "id": "s2draw",
   "page": 18,
   "kind": "work",
   "tab": "Step 2",
   "overline": null,
   "title": "Draw the system again",
   "lead": null,
   "zones": [],
   "texts": [
    "Across both pages. The same case, arranged this time by the layers, the actors, and the descriptions you have just defined. Put the actors in bands by layer, widest scope of decision at the top. Draw a line between two actors where one needs a resource from the other, and mark where two actors read the problem differently. Write the three sentences on the right.",
    "Draw the system again",
    "Exercise 10",
    "Step 2"
   ]
  },
  "s2draw2": {
   "id": "s2draw2",
   "page": 19,
   "kind": "work",
   "tab": "Step 2",
   "overline": null,
   "title": null,
   "lead": null,
   "zones": [],
   "texts": [
    "1.",
    "1. What this system produces, whether or not anyone intends it. Read the bands: what does the arrangement reliably hand out, and to whom?",
    "2.",
    "2. Where the disagreement is. Take the two descriptions from Exercise 8 that cannot both be acted on, and say who holds each and what each one wants.",
    "3.",
    "3. What surprised you when you drew it. A missing line, an actor with nothing, a layer that turned out to hold nothing.",
    "Exercise 11",
    "Revised on",
    "Revised on because",
    "Step 2",
    "Three sentences about what you have drawn",
    "What surprised you when you drew it. A missing line, an actor with nothing, a layer that turned out to hold nothing.",
    "What this system produces, whether or not anyone intends it. Read the bands: what does the arrangement reliably hand out, and to whom?",
    "Where the disagreement is. Take the two descriptions from Exercise 8 that cannot both be acted on, and say who holds each and what each one wants.",
    "because"
   ]
  },
  "s3instr": {
   "id": "s3instr",
   "page": 20,
   "kind": "instruction",
   "tab": "Step 3",
   "overline": "Step 3 · before you draw",
   "title": "Describe behaviour over time",
   "lead": [
    "To show the pattern the system produces. This is the first step that looks at the case as something that has been happening rather than as something that is the case."
   ],
   "blocks": [
    {
     "h": [
      "Behaviour means the system's, not anyone's conduct"
     ]
    },
    {
     "p": [
      "It is the path a quantity has taken over time, and nothing about how people acted. Writing about officials being slow is answering a different question."
     ]
    },
    {
     "h": [
      "What to graph"
     ]
    },
    {
     "p": [
      {
       "b": [
        "What is measured is fixed. How you measure it is yours."
       ]
      },
      " The thing the graph is about is the one the agreed problem definition names: the thing there is too much or too little of. That does not change here, because changing it is how a case quietly changes subject, and nobody notices afterwards because everything that follows is consistent with whatever was graphed."
     ]
    },
    {
     "p": [
      "The measure is a separate choice, and it is yours. One thing can usually be counted several ways, and you take whichever count has a history you can draw: a waiting list, the number of people in emergency accommodation, and nights of shelter used are three measures of one thing. Write down which measure you are using, and why that one. If no measure of the named thing can be found at all, the thing named is not a quantity, which is a return to Step 1 rather than a fault in this step."
     ]
    },
    {
     "p": [
      "If the agreed problem definition used one of the other forms, graph the quantity that the definition compares against something. For a ",
      {
       "b": [
        "mismatch"
       ]
      },
      ", graph the amount available in the place where the need is. For ",
      {
       "b": [
        "falling short of a standard"
       ]
      },
      ", graph the measured level of the thing the standard is about. For ",
      {
       "b": [
        "not happened yet"
       ]
      },
      ", there is no series to draw, so graph the nearest quantity that does have a history: the pressure that would produce the risk, or the capacity that would absorb it, and say why that is the nearest one available."
     ]
    },
    {
     "h": [
      "The period goes back to the last time the system changed"
     ]
    },
    {
     "p": [
      "Back to the last major change (a reform, a crisis, a new instrument, a change of government with a policy attached), or roughly ten years, whichever is longer. Not for thoroughness: a period that starts after the last reform shows the system settling down, which looks like stability, and an explanation built for stability explains the wrong thing. Use intervals as coarse as the evidence allows. Yearly is usually enough, and monthly usually produces noise you will then try to explain."
     ]
    },
    {
     "h": [
      "This step tests Step 1"
     ]
    },
    {
     "p": [
      "Step 1's second rule was to name a thing that can rise or fall. Here that claim is put to the test."
     ]
    },
    {
     "table": {
      "head": [
       [
        "If this happens"
       ],
       [
        "Go back to"
       ]
      ],
      "rows": [
       [
        [
         "The line cannot be drawn, because the quantity does not move"
        ],
        [
         "Step 1, page ",
         {
          "ref": "s1work2"
         },
         ", and rename the thing. What was named is a condition or a judgement, not a quantity"
        ]
       ],
       [
        [
         "The line can be drawn, but it is not the problem"
        ],
        [
         "Step 1, page ",
         {
          "ref": "s1work2"
         },
         ". The problem definition named a proxy"
        ]
       ],
       [
        [
         "The period has to reach outside your boundary"
        ],
        [
         "Step 2, page ",
         {
          "ref": "s2work1"
         },
         ", and reopen the exclusions"
        ]
       ]
      ]
     }
    },
    {
     "p": [
      "This is the commonest return in the whole process, and going back here costs very little."
     ]
    },
    {
     "opposite": [
      "Opposite: Exercises 1 to 4"
     ]
    }
   ]
  },
  "s3work1": {
   "id": "s3work1",
   "page": 21,
   "kind": "work",
   "tab": "Step 3",
   "overline": "Step 3 · your page",
   "title": "The pattern",
   "lead": null,
   "zones": [
    {
     "number": "1",
     "label": "Exercise 1",
     "title": "What you are graphing",
     "hints": [],
     "hintsInline": [],
     "texts": [
      "1",
      "Exercise 1",
      "How you are measuring it, and why that measure",
      "Not happened yet: why the quantity graphed is the nearest",
      "The period starts at",
      "The period starts at because",
      "The thing measured, from the agreed problem definition",
      "What you are graphing",
      "because"
     ]
    },
    {
     "number": "2",
     "label": "Exercise 2",
     "title": "The line",
     "hints": [],
     "hintsInline": [],
     "texts": [
      "2",
      "Exercise 2",
      "From",
      "Fromto",
      "The line",
      "The quantity above",
      "to"
     ]
    },
    {
     "number": "3",
     "label": "Exercise 3",
     "title": "What happened, and when",
     "hints": [
      "Reforms, crises, new instruments, court rulings, and every previous attempt to fix this. Line them up under the years they happened."
     ],
     "hintsInline": [
      [
       "Reforms, crises, new instruments, court rulings, and every previous attempt to fix this. Line them up under the years they happened."
      ]
     ],
     "texts": [
      "3",
      "Exercise 3",
      "Reforms, crises, new instruments, court rulings, and every previous attempt to fix this. Line them up under the years they happened.",
      "Six cells. If there were more,",
      "Six cells. If there were more,in total, and these are the ones that mattered.",
      "What happened, and when",
      "in total, and these are the ones that mattered."
     ]
    },
    {
     "number": "4",
     "label": "Exercise 4",
     "title": "Where the line comes from",
     "hints": [
      "Mark each part of the line. An unlabelled mixture is the one thing that is not allowed."
     ],
     "hintsInline": [
      [
       "Mark each part of the line. An unlabelled mixture is the one thing that is not allowed."
      ]
     ],
     "texts": [
      "4",
      "Documented, from accounts",
      "Estimated, our own reading",
      "Exercise 4",
      "Mark each part of the line. An unlabelled mixture is the one thing that is not allowed.",
      "Measured, a published series",
      "Measured, a published series Documented, from accounts Estimated, our own reading",
      "Where the line comes from"
     ]
    }
   ],
   "texts": [
    "1",
    "2",
    "3",
    "4",
    "Documented, from accounts",
    "Estimated, our own reading",
    "Exercise 1",
    "Exercise 2",
    "Exercise 3",
    "Exercise 4",
    "From",
    "Fromto",
    "How you are measuring it, and why that measure",
    "Mark each part of the line. An unlabelled mixture is the one thing that is not allowed.",
    "Measured, a published series",
    "Measured, a published series Documented, from accounts Estimated, our own reading",
    "Not happened yet: why the quantity graphed is the nearest",
    "Reforms, crises, new instruments, court rulings, and every previous attempt to fix this. Line them up under the years they happened.",
    "Revised on",
    "Revised on because",
    "Six cells. If there were more,",
    "Six cells. If there were more,in total, and these are the ones that mattered.",
    "Step 3",
    "Step 3 · your page",
    "The line",
    "The pattern",
    "The period starts at",
    "The period starts at because",
    "The quantity above",
    "The thing measured, from the agreed problem definition",
    "What happened, and when",
    "What you are graphing",
    "Where the line comes from",
    "because",
    "in total, and these are the ones that mattered.",
    "to"
   ]
  },
  "s3ref": {
   "id": "s3ref",
   "page": 22,
   "kind": "instruction",
   "tab": "Step 3",
   "overline": "Step 3 · before Exercises 5 to 7",
   "title": "Shapes, evidence, and the system problem definition",
   "lead": null,
   "blocks": [
    {
     "h": [
      "The six shapes"
     ]
    },
    {
     "p": [
      "Pick the one that describes your graph, and then describe why your graph is that shape. A shape you choose is a claim about the system. A shape you describe in your own words is a caption."
     ]
    },
    {
     "table": {
      "head": [
       [
        "Shape"
       ],
       [
        "What the line does"
       ]
      ],
      "rows": [
       [
        [
         {
          "b": [
           "Steady rise or fall"
          ]
         }
        ],
        [
         "Moves one way at roughly the same rate"
        ]
       ],
       [
        [
         {
          "b": [
           "Accelerating"
          ]
         }
        ],
        [
         "Moves one way, faster and faster"
        ]
       ],
       [
        [
         {
          "b": [
           "Levelling off"
          ]
         }
        ],
        [
         "Moves one way, then flattens towards a limit"
        ]
       ],
       [
        [
         {
          "b": [
           "Up and down"
          ]
         }
        ],
        [
         "Repeatedly overshoots and comes back"
        ]
       ],
       [
        [
         {
          "b": [
           "Rise then collapse"
          ]
         }
        ],
        [
         "Grows, turns, and falls below where it started"
        ]
       ],
       [
        [
         {
          "b": [
           "Flat"
          ]
         }
        ],
        [
         "Does not move, despite the pressure on it"
        ]
       ]
      ]
     }
    },
    {
     "template": [
      {
       "b": [
        "Flat is a pattern, not a failure."
       ]
      },
      " A quantity that stays put while people push on it is being held there by something, and naming what holds it is the work that follows. Most problems that have survived several attempts are this shape."
     ]
    },
    {
     "h": [
      "Evidence is labelled, not ranked"
     ]
    },
    {
     "p": [
      "A line drawn from documented accounts is a legitimate graph. What matters is that the reader can tell which kind each part of the line is. Where the line changes kind, mark the change."
     ]
    },
    {
     "table": {
      "head": [
       [
        "Kind"
       ],
       [
        "What you write beside the line"
       ]
      ],
      "rows": [
       [
        [
         {
          "b": [
           "Measured"
          ]
         }
        ],
        [
         "The source and the years it covers"
        ]
       ],
       [
        [
         {
          "b": [
           "Documented"
          ]
         }
        ],
        [
         "The documents, and what each one establishes about direction or timing"
        ]
       ],
       [
        [
         {
          "b": [
           "Estimated"
          ]
         }
        ],
        [
         "What the estimate rests on, and the words \"this line is an estimate\""
        ]
       ]
      ]
     }
    },
    {
     "h": [
      "The system problem definition"
     ]
    },
    {
     "p": [
      "One sentence naming the pattern. It is a different sentence from the problem definition on page ",
      {
       "ref": "s1work2"
      },
      ": that one says what is wrong, and this one says what the system keeps doing."
     ]
    },
    {
     "template": [
      "Since ",
      {
       "b": [
        "[when]"
       ]
      },
      ", ",
      {
       "b": [
        "[the quantity]"
       ]
      },
      " has ",
      {
       "b": [
        "[shape]"
       ]
      },
      ", and ",
      {
       "b": [
        "[what has been tried]"
       ]
      },
      " has not changed it."
     ]
    },
    {
     "h": [
      "The two futures"
     ]
    },
    {
     "p": [
      "Optional, and drawn on the same axes as the line. One dotted line for what you expect to happen if nothing changes, and one for what the desired change from Step 1 would look like if it happened. Neither is a prediction. Both are drawn before anything has been chosen, which is the point: they fix what better would look like as a shape, while nobody is yet attached to a particular way of getting there."
     ]
    },
    {
     "opposite": [
      "Opposite: Exercises 5 to 7"
     ]
    }
   ]
  },
  "s3work2": {
   "id": "s3work2",
   "page": 23,
   "kind": "work",
   "tab": "Step 3",
   "overline": "Step 3 · your page",
   "title": "The shape, and what it means",
   "lead": null,
   "zones": [
    {
     "number": "5",
     "label": "Exercise 5",
     "title": "The shape of the line",
     "hints": [
      "Why your graph is that shape."
     ],
     "hintsInline": [
      [
       "Why your graph is that shape."
      ]
     ],
     "texts": [
      "5",
      "Accelerating",
      "Exercise 5",
      "Flat",
      "Levelling off",
      "Rise then collapse",
      "Steady rise or fall",
      "Steady rise or fall Accelerating Levelling off Up and down Rise then collapse Flat",
      "The shape of the line",
      "Up and down",
      "Why your graph is that shape."
     ]
    },
    {
     "number": "6",
     "label": "Exercise 6",
     "title": "The system problem definition",
     "hints": [],
     "hintsInline": [],
     "texts": [
      "6",
      "Exercise 6",
      "Since",
      "The system problem definition",
      "and",
      "andhas not changed it.",
      "has",
      "has not changed it.",
      "the quantity",
      "the shape",
      "what has been tried",
      "when the period starts"
     ]
    },
    {
     "number": "7",
     "label": "Exercise 7",
     "title": "The two futures, and any other quantity",
     "hints": [
      "Optional. On the left, a dotted line for what you expect to happen if nothing changes, and a second for what the desired change would look like. Use the right-hand box for one further quantity, where the agreed problem definition rests on it."
     ],
     "hintsInline": [
      [
       "Optional. On the left, a dotted line for what you expect to happen if nothing changes, and a second for what the desired change would look like. Use the right-hand box for one further quantity, where the agreed problem definition rests on it."
      ]
     ],
     "texts": [
      "7",
      "Another quantity",
      "Exercise 7",
      "Optional. On the left, a dotted line for what you expect to happen if nothing changes, and a second for what the desired change would look like. Use the right-hand box for one further quantity, where the agreed problem definition rests on it.",
      "The same quantity",
      "The two futures, and any other quantity"
     ]
    }
   ],
   "texts": [
    "5",
    "6",
    "7",
    "Accelerating",
    "Another quantity",
    "Exercise 5",
    "Exercise 6",
    "Exercise 7",
    "Flat",
    "Levelling off",
    "Optional. On the left, a dotted line for what you expect to happen if nothing changes, and a second for what the desired change would look like. Use the right-hand box for one further quantity, where the agreed problem definition rests on it.",
    "Revised on",
    "Revised on because",
    "Rise then collapse",
    "Since",
    "Steady rise or fall",
    "Steady rise or fall Accelerating Levelling off Up and down Rise then collapse Flat",
    "Step 3",
    "Step 3 · your page",
    "The same quantity",
    "The shape of the line",
    "The shape, and what it means",
    "The system problem definition",
    "The two futures, and any other quantity",
    "Up and down",
    "Why your graph is that shape.",
    "and",
    "andhas not changed it.",
    "because",
    "has",
    "has not changed it.",
    "the quantity",
    "the shape",
    "what has been tried",
    "when the period starts"
   ]
  },
  "checks": {
   "id": "checks",
   "page": 24,
   "kind": "instruction",
   "tab": "Phase A",
   "overline": "Before you leave Phase A",
   "title": "The critical checks",
   "lead": [
    "Checked by you. Nobody signs them off. A line that cannot be ticked off sends you back to the page named beside it, and going back is free."
   ],
   "blocks": [
    {
     "h": [
      "Step 1 is complete when"
     ]
    },
    {
     "list": [
      [
       "The agreed problem definition states a situation, not a solution: what is wrong with something valued, with the reason it matters and for whom."
      ],
      [
       "Your position is named."
      ],
      [
       "The desired change is stated after the problem, not before it, in the same terms as the agreed problem definition."
      ],
      [
       "The four questions in Exercise 3 are answered, and a known procedure would not solve the problem."
      ],
      [
       "Potential solutions that occurred to you are in Exercise 8, not in the agreed problem definition."
      ]
     ],
     "ordered": false
    },
    {
     "h": [
      "Step 2 is complete when"
     ]
    },
    {
     "list": [
      [
       "What is excluded is written down, with a reason and a mark of F, O, or I."
      ],
      [
       "The actors include those affected by the system but not involved in it."
      ],
      [
       "Every actor sits in one layer and carries one type."
      ],
      [
       "For every actor, the resources held are recorded. For the actors the dependency question applies to, who needs each resource from them is recorded as well."
      ],
      [
       "Which layer can take the decision, which is tasked with carrying the decision out, and which answers for the result, are each named or recorded as nobody."
      ],
      [
       "At least two descriptions of the problem are recorded, and they differ in a way that matters."
      ],
      [
       "The system has been drawn on a large sheet, drawn again in this book, and its three sentences written."
      ]
     ],
     "ordered": false
    },
    {
     "h": [
      "Step 3 is complete when"
     ]
    },
    {
     "list": [
      [
       "The quantity graphed measures the thing named in the agreed problem definition, and a line says which measure it is and why that one."
      ],
      [
       "The period reaches back to the last major change in the system, or ten years, and a line says which."
      ],
      [
       "The line carries its evidence, with each part marked measured, documented, or estimated."
      ],
      [
       "What has been tried is on the event strip, with the years."
      ],
      [
       "The shape is named, with a line saying why the graph is that shape."
      ],
      [
       "The system problem definition is written, and it is not the agreed problem definition reworded."
      ]
     ],
     "ordered": false
    },
    {
     "opposite": [
      "Opposite: what carries forward"
     ]
    }
   ],
   "checks": [
    {
     "heading": "Step 1 is complete when",
     "criteria": [
      "The agreed problem definition states a situation, not a solution: what is wrong with something valued, with the reason it matters and for whom.",
      "Your position is named.",
      "The desired change is stated after the problem, not before it, in the same terms as the agreed problem definition.",
      "The four questions in Exercise 3 are answered, and a known procedure would not solve the problem.",
      "Potential solutions that occurred to you are in Exercise 8, not in the agreed problem definition."
     ]
    },
    {
     "heading": "Step 2 is complete when",
     "criteria": [
      "What is excluded is written down, with a reason and a mark of F, O, or I.",
      "The actors include those affected by the system but not involved in it.",
      "Every actor sits in one layer and carries one type.",
      "For every actor, the resources held are recorded. For the actors the dependency question applies to, who needs each resource from them is recorded as well.",
      "Which layer can take the decision, which is tasked with carrying the decision out, and which answers for the result, are each named or recorded as nobody.",
      "At least two descriptions of the problem are recorded, and they differ in a way that matters.",
      "The system has been drawn on a large sheet, drawn again in this book, and its three sentences written."
     ]
    },
    {
     "heading": "Step 3 is complete when",
     "criteria": [
      "The quantity graphed measures the thing named in the agreed problem definition, and a line says which measure it is and why that one.",
      "The period reaches back to the last major change in the system, or ten years, and a line says which.",
      "The line carries its evidence, with each part marked measured, documented, or estimated.",
      "What has been tried is on the event strip, with the years.",
      "The shape is named, with a line saying why the graph is that shape.",
      "The system problem definition is written, and it is not the agreed problem definition reworded."
     ]
    }
   ]
  },
  "carries": {
   "id": "carries",
   "page": 25,
   "kind": "summary",
   "tab": "Phase A",
   "overline": "Phase A",
   "title": "What carries forward",
   "lead": [
    "The agreed version, copied here. Everything the rest of the process needs from Phase A is on this page, so this is the only page to find again. The page each item was decided on is printed beside it."
   ],
   "zones": [
    {
     "number": "1",
     "label": null,
     "title": "The problem definition, as agreed",
     "hints": [
      "Decided on page {p:s1work2}."
     ],
     "hintsInline": [
      [
       "Decided on page ",
       {
        "ref": "s1work2"
       },
       "."
      ]
     ],
     "texts": [
      ".",
      "1",
      "Decided on page",
      "Decided on page {p:s1work2}.",
      "The problem definition, as agreed"
     ]
    },
    {
     "number": "2",
     "label": null,
     "title": "The desired change, and your position",
     "hints": [
      "Decided on page {p:s1work}."
     ],
     "hintsInline": [
      [
       "Decided on page ",
       {
        "ref": "s1work"
       },
       "."
      ]
     ],
     "texts": [
      ".",
      "2",
      "Decided on page",
      "Decided on page {p:s1work}.",
      "The desired change, and your position"
     ]
    },
    {
     "number": "3",
     "label": null,
     "title": "The boundary, in one sentence, and the exclusion most likely to be wrong",
     "hints": [
      "Decided on page {p:s2work1}."
     ],
     "hintsInline": [
      [
       "Decided on page ",
       {
        "ref": "s2work1"
       },
       "."
      ]
     ],
     "texts": [
      ".",
      "3",
      "Decided on page",
      "Decided on page {p:s2work1}.",
      "The boundary, in one sentence, and the exclusion most likely to be wrong"
     ]
    },
    {
     "number": "4",
     "label": null,
     "title": "The layers, and who holds the decision",
     "hints": [
      "Decided on pages {p:s2work1} and {p:s2work3}. Each layer keeps its row from page {p:s2work1}."
     ],
     "hintsInline": [
      [
       "Decided on pages ",
       {
        "ref": "s2work1"
       },
       " and ",
       {
        "ref": "s2work3"
       },
       ". Each layer keeps its row from page ",
       {
        "ref": "s2work1"
       },
       "."
      ]
     ],
     "texts": [
      ".",
      ". Each layer keeps its row from page",
      "1",
      "2",
      "3",
      "4",
      "5",
      "Accountability",
      "Authority",
      "Decided on pages",
      "Decided on pages {p:s2work1} and {p:s2work3}. Each layer keeps its row from page {p:s2work1}.",
      "Responsibility",
      "The layers, and who holds the decision",
      "and"
     ]
    },
    {
     "number": "5",
     "label": null,
     "title": "The two descriptions that disagree",
     "hints": [
      "Decided on page {p:s2work3}. Name the actor holding each."
     ],
     "hintsInline": [
      [
       "Decided on page ",
       {
        "ref": "s2work3"
       },
       ". Name the actor holding each."
      ]
     ],
     "texts": [
      ". Name the actor holding each.",
      "5",
      "Decided on page",
      "Decided on page {p:s2work3}. Name the actor holding each.",
      "The two descriptions that disagree"
     ]
    },
    {
     "number": "6",
     "label": null,
     "title": "The three sentences about the drawing",
     "hints": [
      "Written on page {p:s2draw2}."
     ],
     "hintsInline": [
      [
       "Written on page ",
       {
        "ref": "s2draw2"
       },
       "."
      ]
     ],
     "texts": [
      ".",
      "6",
      "The three sentences about the drawing",
      "Written on page",
      "Written on page {p:s2draw2}."
     ]
    },
    {
     "number": "7",
     "label": null,
     "title": "The system problem definition, and the shape",
     "hints": [
      "Written on page {p:s3work2}."
     ],
     "hintsInline": [
      [
       "Written on page ",
       {
        "ref": "s3work2"
       },
       "."
      ]
     ],
     "texts": [
      ".",
      "7",
      "The system problem definition, and the shape",
      "Written on page",
      "Written on page {p:s3work2}."
     ]
    }
   ],
   "texts": [
    ".",
    ". Each layer keeps its row from page",
    ". Name the actor holding each.",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "Accountability",
    "Authority",
    "Decided on page",
    "Decided on page {p:s1work2}.",
    "Decided on page {p:s1work}.",
    "Decided on page {p:s2work1}.",
    "Decided on page {p:s2work3}. Name the actor holding each.",
    "Decided on pages",
    "Decided on pages {p:s2work1} and {p:s2work3}. Each layer keeps its row from page {p:s2work1}.",
    "Phase A",
    "Responsibility",
    "Revised on",
    "Revised on because",
    "The agreed version, copied here. Everything the rest of the process needs from Phase A is on this page, so this is the only page to find again. The page each item was decided on is printed beside it.",
    "The boundary, in one sentence, and the exclusion most likely to be wrong",
    "The desired change, and your position",
    "The layers, and who holds the decision",
    "The problem definition, as agreed",
    "The system problem definition, and the shape",
    "The three sentences about the drawing",
    "The two descriptions that disagree",
    "What carries forward",
    "Written on page",
    "Written on page {p:s2draw2}.",
    "Written on page {p:s3work2}.",
    "and",
    "because"
   ]
  },
  "notes": {
   "id": "notes",
   "page": 26,
   "kind": "work",
   "tab": "Notes",
   "overline": "Summary and notes",
   "title": "Notes",
   "lead": [
    "Questions you could not answer, sources to find, disagreements the group did not settle, and anything worth keeping that has no working page of its own."
   ],
   "zones": [],
   "texts": [
    "Notes",
    "Questions you could not answer, sources to find, disagreements the group did not settle, and anything worth keeping that has no working page of its own.",
    "Summary and notes"
   ]
  },
  "notes2": {
   "id": "notes2",
   "page": 27,
   "kind": "work",
   "tab": "Notes",
   "overline": "Summary and notes",
   "title": "Notes",
   "lead": null,
   "zones": [],
   "texts": [
    "Notes",
    "Summary and notes"
   ]
  },
  "backcover": {
   "id": "backcover",
   "page": 28,
   "kind": "work",
   "tab": null,
   "overline": "A systems thinking process for policy and intervention design",
   "title": null,
   "lead": null,
   "zones": [],
   "texts": [
    ". Chelsea Green Publishing.",
    "A systems thinking process for policy and intervention design",
    "Drafted for the International Public Policy and Leadership programme, The Hague University of Applied Sciences.",
    "Meadows, D. H. (2008).",
    "Meadows, D. H. (2008). Thinking in systems: A primer. Chelsea Green Publishing.",
    "Phase A workbook. Steps 1 to 3 of thirteen. The later phases are added as they are written.",
    "Thinking in systems: A primer"
   ]
  }
 }
};
